apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: default
  labels:
    app: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: default
  labels:
    app: gitlab-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: default
  labels:
    app: gitlab-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: default
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:14.9.3-ce.0
          resources:
            requests:
              memory: 4Gi
              cpu: "4"
              ephemeral-storage: 2Gi
            limits:
              memory: 4Gi
              cpu: "4"
              ephemeral-storage: 2Gi
          livenessProbe:
            # httpGet:
            #   path: /-/liveness
            #   port: 80
            # initialDelaySeconds: 2160
            # timeoutSeconds: 5
            exec:
              command:
                - ls
          readinessProbe:
            # httpGet:
            #   path: /-/readiness
            #   port: 80
            # initialDelaySeconds: 360
            # timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          env:
            # TODO: Configure prometheus
            - name: GITLAB_OMNIBUS_CONFIG
              value: "prometheus['monitor_kubernetes'] = false"
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: postgres
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: gitlab-data
            - mountPath: /var/log/gitlab
              name: gitlab-logs
            - mountPath: /etc/gitlab
              name: gitlab-config
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config
