apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: default
  labels:
    app: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: default
  labels:
    app: gitlab-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: default
  labels:
    app: gitlab-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: default
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    # Avoid resource locking on PVCs
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:14.9.3-ce.0
          resources:
            requests:
              memory: 4Gi
              cpu: "4"
              ephemeral-storage: 3Gi
            limits:
              memory: 4Gi
              cpu: "4"
              ephemeral-storage: 3Gi
          livenessProbe:
            httpGet:
              path: /-/liveness
              port: 80
            initialDelaySeconds: 1500
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: 80
            initialDelaySeconds: 1200
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 50
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          env:
            # TODO: Configure prometheus
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                prometheus['monitor_kubernetes'] = false
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "postgres"
                gitlab_rails['db_password'] = "password"
                gitlab_rails['db_host'] = "postgres.default.svc.cluster.local"
                gitlab_rails['db_database'] = "postgres"
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: gitlab-data
            - mountPath: /var/log/gitlab
              name: gitlab-logs
            - mountPath: /etc/gitlab
              name: gitlab-config
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config
