apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: default
  labels:
    app: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: default
  labels:
    app: gitlab-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: default
  labels:
    app: gitlab-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: default
spec:
  selector:
    app: gitlab
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: ssh
      protocol: TCP
      port: 22
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitlab
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: default
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    # Avoid resource locking on PVCs
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:14.9.3-ce.0
          resources:
            requests:
              memory: 4Gi
              cpu: 1
              ephemeral-storage: 500Mi
            limits:
              memory: 4Gi
              cpu: 1
              ephemeral-storage: 500Mi
          livenessProbe:
            httpGet:
              path: /-/liveness
              port: 80
            initialDelaySeconds: 600
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 100
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          env:
            # TODO: Configure prometheus
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
                prometheus['enable'] = false
                grafana['enable'] = false
                postgresql['enable'] = false
                redis['enable'] = false
                gitlab_rails['db_username'] = "postgres"
                gitlab_rails['db_password'] = "password"
                gitlab_rails['db_host'] = "postgres.default.svc.cluster.local"
                gitlab_rails['db_database'] = "postgres"
                gitlab_rails['redis_host'] = "redis.default.svc.cluster.local"
                gitlab_rails['redis_port'] = 6379
            - name: GITLAB_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: gitlab-data
            - mountPath: /var/log/gitlab
              name: gitlab-logs
            - mountPath: /etc/gitlab
              name: gitlab-config
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config
