apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.2
          resources:
            requests:
              memory: 512Mi
              cpu: "0.5"
              ephemeral-storage: 100Mi
            limits:
              memory: 512Mi
              cpu: "0.5"
              ephemeral-storage: 100Mi
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 27017
              name: mongo
          # env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: root
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: password
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["mongo", "--eval", "printjson(rs.initiate())"]
